//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dm2.rc
//
#define IDD_DM2                         101
#define IDD_DM2_GENERAL                 102
#define IDD_DM2_ABOUT                   103
#define IDD_DM2_ADVANCE                 104
#define IDD_DM2_HOTKEY                  105
#define IDD_DM2_FAVMENU                 106
#define IDD_DM2_MANAGER                 107
#define IDD_DM2_CUSTOM                  108
#define IDD_DM2_CUSTOM_EDIT             109
#define IDD_DM2_EXCEPTION               110
#define IDD_DM2_EXCEPTION_EDIT          111
#define IDR_JPEG_DM2                    111
#define IDD_DM2_FAVMENU_EDIT            112
#define IDI_TREE                        112
#define IDD_DM2_FAVMENUITEM_EDIT        113
#define IDI_TREEITEM                    113
#define IDD_DM2_HOTKEY_EDIT             114
#define IDR_MENU_RESIZE                 114
#define IDD_DM2_PLUGINS                 115
#define IDD_DM2_ACTION                  116
#define IDD_DM2_ACTION_RESIZEWIN        118
#define IDD_DM2_ACTION_ALIGN            119
#define IDB_BITMAP_ALIGN                120
#define IDC_BTN_EXIT                    1000
#define IDC_TREE_SET                    1001
#define IDC_STATIC_DLG                  1002
#define IDC_STATIC_TITLE                1003
#define IDC_CHK_FLOATTOP                1004
#define IDC_LIST_DM2WIN                 1005
#define IDC_BTN_SHOW                    1006
#define IDC_BTN_CLOSE                   1007
#define IDC_BTN_SHOWALL                 1008
#define IDC_BTN_REF                     1009
#define IDC_CHK_FOLLOWMODE              1009
#define IDC_CHK_OPA                     1010
#define IDC_COMBO_OPA                   1011
#define IDC_COMBO_POS                   1012
#define IDC_EDIT_BC                     1013
#define IDC_EDIT_BGC                    1014
#define IDC_CHK_MSS                     1015
#define IDC_EDIT_SSW                    1016
#define IDC_EDIT_SSH                    1017
#define IDC_CHK_TRAY                    1018
#define IDC_CHK_SF                      1019
#define IDC_CHK_EH                      1020
#define IDC_LIST_HOTKEY                 1021
#define IDC_BTN_HKADD                   1022
#define IDC_BTN_HKDEL                   1023
#define IDC_BTN_HKEDIT                  1024
#define IDC_CHK_MSM                     1025
#define IDC_CHK_DWC                     1026
#define IDC_CHK_DYNT                    1027
#define IDC_CHK_EF                      1028
#define IDC_BTN_EXADD                   1029
#define IDC_BTN_EXDEL                   1030
#define IDC_BTN_EXEDIT                  1031
#define IDC_BTN_CADD                    1032
#define IDC_BTN_EXMADD                  1032
#define IDC_BTN_CDEL                    1033
#define IDC_BTN_EXMDEL                  1033
#define IDC_BTN_CEDIT                   1034
#define IDC_BTN_EXEDIT2                 1034
#define IDC_BTN_EXMEDIT                 1034
#define IDC_LIST_CUSTOM                 1035
#define IDC_CHK_RUN                     1036
#define IDC_BTN_CTEST                   1036
#define IDC_COMBO_RUNMODE               1037
#define IDC_EDIT_RN                     1038
#define IDC_EDIT_RE                     1039
#define IDC_CHK_HKDM2                   1040
#define IDC_HOTKEY_DM2                  1041
#define IDC_CHK_MO                      1046
#define IDC_LIST_MENU                   1047
#define IDC_LIST_EXCEPTION              1051
#define IDC_EDIT_RULE                   1052
#define IDC_RADIO_TEXT                  1053
#define IDC_RADIO_PROC                  1054
#define IDC_CHK_DF                      1055
#define IDC_CHK_DDM                     1056
#define IDC_BTN_EADD                    1057
#define IDC_BTN_EDEL                    1058
#define IDC_BTN_EEDIT                   1059
#define IDC_EDIT_SECTION                1060
#define IDC_EDIT_PATH                   1061
#define IDC_EDIT_NAME                   1062
#define IDC_BTN_BRW                     1063
#define IDC_CHK_SUB                     1064
#define IDC_BTN_BC                      1065
#define IDC_BTN_BGC                     1066
#define IDC_CHK_SEP                     1066
#define IDC_CHK_FAVCMP                  1067
#define IDC_HOTKEY_EDIT                 1068
#define IDC_COMBO_CMD                   1069
#define IDC_BTN_HELP                    1070
#define IDC_BTN_CONFIG                  1072
#define IDC_BTN_ABOUT                   1073
#define IDC_LIST_PLUGINS                1074
#define IDC_BTN_UNINST                  1075
#define IDC_STATIC_FPOS                 1077
#define IDC_STATIC_FBC                  1078
#define IDC_STATIC_FBGC                 1079
#define IDC_STATIC_SW                   1080
#define IDC_STATIC_SH                   1081
#define IDC_STATIC_HK                   1082
#define IDC_STATIC_HK_CMD               1083
#define IDC_STATIC_SEC                  1084
#define IDC_STATIC_NAME                 1085
#define IDC_STATIC_PATH                 1086
#define IDC_STATIC_CUSTOM               1087
#define IDC_STATIC_RN                   1088
#define IDC_STATIC_RE                   1089
#define IDC_STATIC_CST                  1090
#define IDC_STATIC_EXCEPT               1091
#define IDC_STATIC_RULE                 1092
#define IDC_STATIC_CW                   1093
#define IDC_STATIC_ES                   1094
#define IDC_STATIC_LANG                 1095
#define IDC_COMBO_LANG                  1097
#define IDC_STATIC_GETLANG              1098
#define IDC_STATIC_SS                   1099
#define IDC_STATIC_GETPLUG              1101
#define IDC_STATIC_HOME                 1103
#define IDC_STATIC_HURL                 1104
#define IDC_STATIC_EMAIL                1105
#define IDC_STATIC_EURL                 1106
#define IDC_CHK_DSYS                    1107
#define IDC_STATIC_FSIZE                1108
#define IDC_COMBO_FSIZE                 1110
#define IDC_STATIC_PARAM                1111
#define IDC_EDIT_HKPARAM                1112
#define IDC_CHK_MOVE                    1113
#define IDC_STATIC_KM                   1115
#define IDC_STATIC_NCMIN                1116
#define IDC_STATIC_NCMAX                1117
#define IDC_STATIC_NCCLS                1118
#define IDC_STATIC_REC                  1119
#define IDC_STATIC_RC                   1119
#define IDC_EDIT_REC                    1120
#define IDC_STATIC_SRC                  1120
#define IDC_STATIC_ARC                  1121
#define IDC_STATIC_CRC                  1122
#define IDC_STATIC_MC                   1123
#define IDC_STATIC_SMC                  1124
#define IDC_STATIC_AMC                  1125
#define IDC_STATIC_CMC                  1126
#define IDC_TREE_MENUITEM               1126
#define IDC_COMBO_RIB                   1127
#define IDC_EDIT_SHOWPATH               1127
#define IDC_COMBO_RAB                   1128
#define IDC_BUTTON_UP                   1128
#define IDC_COMBO_RCB                   1129
#define IDC_STATIC_W                    1129
#define IDC_COMBO_SRIB                  1130
#define IDC_STATIC_H                    1130
#define IDC_COMBO_SRAB                  1131
#define IDC_EDIT_W                      1131
#define IDC_COMBO_SRCB                  1132
#define IDC_EDIT_H                      1132
#define IDC_COMBO_ARIB                  1133
#define IDC_RADIO_PIX                   1133
#define IDC_COMBO_ARAB                  1134
#define IDC_RADIO_PER                   1134
#define IDC_COMBO_ARCB                  1135
#define IDC_BUTTON_TL                   1135
#define IDC_COMBO_CRIB                  1136
#define IDC_COMBO_CRAB                  1137
#define IDC_COMBO_CRCB                  1138
#define IDC_STATIC_TL                   1138
#define IDC_COMBO_MIB                   1139
#define IDC_STATIC_TC                   1139
#define IDC_COMBO_MAB                   1140
#define IDC_STATIC_TR                   1140
#define IDC_COMBO_MCB                   1141
#define IDC_STATIC_CL                   1141
#define IDC_COMBO_SMIB                  1142
#define IDC_STATIC_CC                   1142
#define IDC_COMBO_SMAB                  1143
#define IDC_STATIC_CR                   1143
#define IDC_COMBO_SMCB                  1144
#define IDC_STATIC_BL                   1144
#define IDC_COMBO_AMIB                  1145
#define IDC_STATIC_BC                   1145
#define IDC_COMBO_AMAB                  1146
#define IDC_STATIC_BR                   1146
#define IDC_COMBO_AMCB                  1147
#define IDC_COMBO_CMIB                  1148
#define IDC_COMBO_CMAB                  1149
#define IDC_COMBO_CMCB                  1150
#define IDC_HOTKEY_EXT                  1151
#define ID_RESIZE_640480                40001
#define ID_RESIZE_800600                40002
#define ID_RESIZE_1024768               40003
#define ID_RESIZE_1280960               40004
#define ID_RESIZE_C100                  40005
#define ID_RESIZE_C50                   40006
#define ID_RESIZE_C30                   40007
#define ID_RESIZE_OTHER                 40008
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1140
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
